"""Repository Interfaces — Protocol-based storage abstractions"""
from typing import Protocol, Any


class AuditEventRepository(Protocol):
    def save(self, data: dict) -> int: ...
    def list_all(self, limit: int = 50) -> list[dict]: ...
    def get_by_event_id(self, event_id: str) -> dict | None: ...
    def find_by_correlation(self, correlation_id: str, limit: int = 200) -> list[dict]: ...


class ScanRunRepository(Protocol):
    def save(self, data: dict) -> int: ...
    def get(self, scan_run_id: str) -> dict | None: ...


class ScannerCandidateRepository(Protocol):
    def save(self, data: dict) -> int: ...
    def list_by_scan(self, scan_run_id: str) -> list[dict]: ...
    def list_included(self, scan_run_id: str) -> list[dict]: ...
    def list_excluded(self, scan_run_id: str) -> list[dict]: ...


class QuantScoreRepository(Protocol):
    def save(self, data: dict) -> int: ...
    def get(self, evaluation_id: str) -> dict | None: ...


class StrategySignalRepository(Protocol):
    def save(self, data: dict) -> int: ...
    def get(self, signal_id: str) -> dict | None: ...


class RiskDecisionRepository(Protocol):
    def save(self, data: dict) -> int: ...
    def get(self, risk_decision_id: str) -> dict | None: ...


class OrderRepository(Protocol):
    def save(self, data: dict) -> int: ...
    def get(self, order_intent_id: str) -> dict | None: ...


class FillRepository(Protocol):
    def save(self, data: dict) -> int: ...
    def get(self, fill_id: str) -> dict | None: ...


class PortfolioSnapshotRepository(Protocol):
    def save(self, data: dict) -> int: ...
    def list_all(self) -> list[dict]: ...


class EodReportRepository(Protocol):
    def save(self, data: dict) -> int: ...
    def get_latest(self) -> dict | None: ...
