"""Risk Types — RiskDecisionStatus and RiskRejectReason"""
from __future__ import annotations

from enum import Enum


class RiskDecisionStatus(str, Enum):
    """Risk Engine 최종 판단 상태"""
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    BLOCKED = "BLOCKED"


class RiskRejectReason(str, Enum):
    """Risk Engine 거절 사유 코드"""
    MARKET_REGIME_BLOCKED = "MARKET_REGIME_BLOCKED"
    SESSION_BLOCKED = "SESSION_BLOCKED"
    QUANT_REJECTED = "QUANT_REJECTED"
    DUPLICATE_ORDER_BLOCKED = "DUPLICATE_ORDER_BLOCKED"
    REENTRY_BLOCKED = "REENTRY_BLOCKED"
    DAILY_LOSS_LIMIT_BLOCKED = "DAILY_LOSS_LIMIT_BLOCKED"
    SYMBOL_EXPOSURE_BLOCKED = "SYMBOL_EXPOSURE_BLOCKED"
    POSITION_LIMIT_BLOCKED = "POSITION_LIMIT_BLOCKED"
    STALE_DATA_BLOCKED = "STALE_DATA_BLOCKED"
    DATA_QUALITY_BLOCKED = "DATA_QUALITY_BLOCKED"
    EMERGENCY_STOP_BLOCKED = "EMERGENCY_STOP_BLOCKED"
    LIVE_TRADING_DISABLED = "LIVE_TRADING_DISABLED"
    SELL_BLOCKED_NO_POSITION = "SELL_BLOCKED_NO_POSITION"
    BUY_BLOCKED_NON_POSITIVE_AMOUNT = "BUY_BLOCKED_NON_POSITIVE_AMOUNT"
    BUY_BLOCKED_LOW_CONFIDENCE = "BUY_BLOCKED_LOW_CONFIDENCE"
    BUY_BLOCKED_MISSING_QUANT_SOURCE = "BUY_BLOCKED_MISSING_QUANT_SOURCE"
    UNKNOWN = "UNKNOWN"
