"""scanner_type enums — ScannerType and ExclusionReason"""
from __future__ import annotations

from enum import Enum


class ScannerType(str, Enum):
    """SAT3 Scanner Type"""
    RAPID_SURGE = "RAPID_SURGE"
    LIQUIDITY_MOMENTUM = "LIQUIDITY_MOMENTUM"
    BREAKOUT = "BREAKOUT"
    PULLBACK_REBOUND = "PULLBACK_REBOUND"


class ExclusionReason(str, Enum):
    """SAT3 Exclusion Reason — 후보 탈락 사유"""

    # Universe / 상품 유형
    NOT_KOSPI_KOSDAQ = "NOT_KOSPI_KOSDAQ"
    NOT_COMMON_STOCK = "NOT_COMMON_STOCK"
    ETF_EXCLUDED = "ETF_EXCLUDED"
    ETN_EXCLUDED = "ETN_EXCLUDED"
    ELW_EXCLUDED = "ELW_EXCLUDED"
    REIT_EXCLUDED = "REIT_EXCLUDED"
    SPAC_EXCLUDED = "SPAC_EXCLUDED"
    PREFERRED_STOCK_EXCLUDED = "PREFERRED_STOCK_EXCLUDED"
    WARRANT_EXCLUDED = "WARRANT_EXCLUDED"
    INVERSE_EXCLUDED = "INVERSE_EXCLUDED"
    LEVERAGED_EXCLUDED = "LEVERAGED_EXCLUDED"
    UNKNOWN_PRODUCT_TYPE = "UNKNOWN_PRODUCT_TYPE"

    # 공통 정량 필터
    PRICE_TOO_HIGH = "PRICE_TOO_HIGH"
    PRICE_TOO_LOW = "PRICE_TOO_LOW"
    TRADING_VALUE_TOO_LOW = "TRADING_VALUE_TOO_LOW"
    VOLUME_TOO_LOW = "VOLUME_TOO_LOW"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    TRADING_HALTED = "TRADING_HALTED"
    MANAGEMENT_ISSUE = "MANAGEMENT_ISSUE"
    INVESTMENT_WARNING = "INVESTMENT_WARNING"
    VI_ACTIVE = "VI_ACTIVE"
    KIS_SOURCE_INVALID = "KIS_SOURCE_INVALID"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"

    # Scanner 특화
    SCANNER_CONDITION_NOT_MET = "SCANNER_CONDITION_NOT_MET"
    MARKET_REGIME_BLOCKED = "MARKET_REGIME_BLOCKED"